# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 22:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=datetime.datetime(2017, 10, 16, 22, 21, 37, 828481))),
                ('item_name', models.CharField(max_length=100)),
                ('item_image', models.CharField(blank=True, max_length=300)),
                ('item_description', models.TextField(blank=True, max_length=1000)),
                ('daily_price_in_dollars', models.PositiveSmallIntegerField(default=0)),
                ('special_time_span_one', models.PositiveSmallIntegerField(default=0)),
                ('special_time_span_two', models.PositiveSmallIntegerField(default=0)),
                ('special_discount_percentage_one', models.PositiveSmallIntegerField(default=0)),
                ('special_discount_percentage_two', models.PositiveSmallIntegerField(default=0)),
                ('category', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
