# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 22:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing_app', '0003_auto_20171016_2223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='created',
        ),
    ]
