# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 23:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing_app', '0004_remove_listing_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 16, 23, 23, 24, 800690)),
        ),
    ]
