# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-17 03:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing_app', '0007_auto_20171017_0234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='slug',
        ),
        migrations.AlterField(
            model_name='listing',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 17, 3, 9, 8, 920249)),
        ),
    ]
