# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-17 21:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing_app', '0008_auto_20171017_0309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 17, 21, 7, 51, 943669)),
        ),
    ]
